export const GAME_CONFIG = {
  canvas: {
    width: 540,
    height: 960,
  },
  world: {
    groundY: 780,
    gravity: 2400,
    backgroundSpeedRatio: 0.34,
    lanePadding: 60,
  },
  player: {
    x: 270,
    width: 88,
    height: 132,
    jumpVelocity: -920,
    stompBounceVelocity: -560,
    coyoteTime: 0.08,
    frameDuration: 0.09,
    collisionInset: {
      x: 20,
      y: 12,
    },
  },
  bull: {
    x: -56,
    y: 690,
    width: 178,
    height: 138,
    frameDuration: 0.1,
    dodgeDuration: 0.42,
  },
  gameOver: {
    caughtDuration: 1.15,
    bullLungeX: 164,
    playerKnockbackX: 42,
    playerKnockbackY: 48,
  },
  obstacles: {
    spawnX: 620,
    initialSpawnX: 900,
    despawnX: -180,
    minGap: 150,
    maxInitialBatch: 3,
    frameDuration: 0.11,
    types: [
      {
        id: 'crate',
        width: 82,
        height: 74,
        frame: 0,
        stompable: true,
        points: 1,
      },
      {
        id: 'barrel',
        width: 82,
        height: 92,
        frame: 1,
        stompable: true,
        points: 1,
      },
      {
        id: 'bench',
        width: 132,
        height: 76,
        frame: 2,
        stompable: false,
        points: 1,
      },
      {
        id: 'fallenRunner',
        width: 142,
        height: 56,
        frame: 3,
        stompable: false,
        points: 1,
      },
      {
        id: 'boxes',
        width: 116,
        height: 106,
        frame: 4,
        stompable: true,
        points: 1,
      },
      {
        id: 'barricade',
        width: 126,
        height: 82,
        frame: 5,
        stompable: false,
        points: 1,
      },
      {
        id: 'runner',
        width: 86,
        height: 128,
        animated: true,
        stompable: false,
        points: 2,
      },
    ],
  },
  difficulty: {
    easy: {
      startSpeed: 260,
      speedRamp: 9,
      startSpawnDelay: 1.45,
      minSpawnDelay: 0.78,
      initialObstacles: 1,
    },
    normal: {
      startSpeed: 330,
      speedRamp: 13,
      startSpawnDelay: 1.18,
      minSpawnDelay: 0.62,
      initialObstacles: 2,
    },
    hard: {
      startSpeed: 400,
      speedRamp: 18,
      startSpawnDelay: 0.92,
      minSpawnDelay: 0.48,
      initialObstacles: 3,
    },
  },
  storage: {
    bestTimeKey: 'sanfermin-runner:best-time',
    languageKey: 'sanfermin-runner:language',
  },
};
