export const GAME_CONFIG = {
  canvas: {
    width: 540,
    height: 960,
  },
  world: {
    groundY: 780,
    gravity: 2400,
    backgroundSpeedRatio: 0.34,
    lanePadding: 60,
  },
  player: {
    x: 270,
    width: 118,
    height: 118,
    jumpVelocity: -920,
    stompBounceVelocity: -560,
    coyoteTime: 0.08,
    frameDuration: 0.08,
    runFrames: [0, 1, 3, 1],
    collisionInset: {
      x: 20,
      y: 12,
    },
  },
  bull: {
    x: -72,
    y: 674,
    width: 218,
    height: 164,
    frameDuration: 0.1,
    dodgeDuration: 0.42,
  },
  gameOver: {
    caughtDuration: 1.25,
    caughtSpeedRatio: 0.82,
    playerKnockbackX: -158,
    playerKnockbackY: 44,
  },
  obstacles: {
    spawnX: 620,
    initialSpawnX: 900,
    despawnX: -180,
    minGap: 150,
    maxInitialBatch: 3,
    frameDuration: 0.11,
    types: [
      {
        id: 'crate',
        width: 90,
        height: 82,
        frame: 0,
        stompable: true,
        points: 1,
      },
      {
        id: 'barrel',
        width: 92,
        height: 102,
        frame: 1,
        stompable: true,
        points: 1,
      },
      {
        id: 'bench',
        width: 146,
        height: 86,
        frame: 2,
        stompable: false,
        points: 1,
      },
      {
        id: 'fallenRunner',
        width: 152,
        height: 64,
        frame: 3,
        stompable: false,
        points: 1,
      },
      {
        id: 'boxes',
        width: 126,
        height: 116,
        frame: 4,
        stompable: true,
        points: 1,
      },
      {
        id: 'barricade',
        width: 142,
        height: 92,
        frame: 5,
        stompable: false,
        points: 1,
      },
      {
        id: 'runner',
        width: 118,
        height: 118,
        animated: true,
        stompable: false,
        points: 2,
      },
    ],
  },
  difficulty: {
    easy: {
      startSpeed: 260,
      speedRamp: 9,
      startSpawnDelay: 1.45,
      minSpawnDelay: 0.78,
      initialObstacles: 1,
    },
    normal: {
      startSpeed: 330,
      speedRamp: 13,
      startSpawnDelay: 1.18,
      minSpawnDelay: 0.62,
      initialObstacles: 2,
    },
    hard: {
      startSpeed: 400,
      speedRamp: 18,
      startSpawnDelay: 0.92,
      minSpawnDelay: 0.48,
      initialObstacles: 3,
    },
  },
  storage: {
    bestTimeKey: 'sanfermin-runner:best-time',
    languageKey: 'sanfermin-runner:language',
  },
};
