export const GAME_CONFIG = {
  canvas: {
    width: 540,
    height: 960,
  },
  world: {
    groundY: 780,
    gravity: 1800,
    backgroundSpeedRatio: 1,
    lanePadding: 60,
  },
  player: {
    x: 188,
    defaultRunner: 'male',
    runnerIds: ['male', 'female'],
    width: 118,
    height: 118,
    fallWidth: 118,
    fallHeight: 118,
    jumpVelocity: -780,
    doubleJumpVelocity: -720,
    stompBounceVelocity: -500,
    coyoteTime: 0.08,
    maxAirJumps: 1,
    frameDuration: 0.08,
    runFrames: [0, 1, 2, 3],
    collisionInset: {
      x: 30,
      y: 22,
    },
  },
  bull: {
    x: -112,
    y: 674,
    width: 218,
    height: 164,
    frameDuration: 0.1,
    dodgeDuration: 0.42,
  },
  gameOver: {
    caughtDuration: 0.95,
    caughtSpeedRatio: 1.15,
    playerKnockbackX: -132,
    playerKnockbackY: 76,
  },
  obstacles: {
    spawnX: 620,
    initialSpawnX: 1040,
    despawnX: -180,
    minGap: 240,
    maxInitialBatch: 3,
    frameDuration: 0.11,
    bullFrameDuration: 0.16,
    types: [
      {
        id: 'crate',
        width: 106,
        height: 96,
        frame: 0,
        stompable: true,
        points: 1,
      },
      {
        id: 'barrel',
        width: 108,
        height: 120,
        frame: 1,
        stompable: true,
        points: 1,
      },
      {
        id: 'bench',
        width: 168,
        height: 100,
        frame: 2,
        stompable: false,
        points: 1,
      },
      {
        id: 'fallenRunner',
        width: 142,
        height: 92,
        frame: 3,
        stompable: false,
        points: 1,
      },
      {
        id: 'boxes',
        width: 146,
        height: 134,
        frame: 4,
        stompable: true,
        points: 1,
      },
      {
        id: 'barricade',
        width: 164,
        height: 106,
        frame: 5,
        stompable: false,
        points: 1,
      },
      {
        id: 'bull',
        y: 674,
        width: 218,
        height: 164,
        animated: true,
        sprite: 'bull',
        stompable: false,
        points: 3,
        collisionInset: {
          x: 0.23,
          y: 0.26,
          width: 0.54,
          height: 0.58,
        },
      },
    ],
  },
  difficulty: {
    easy: {
      startSpeed: 190,
      speedRamp: 5,
      startSpawnDelay: 2.65,
      minSpawnDelay: 1.28,
      initialObstacles: 1,
    },
    normal: {
      startSpeed: 245,
      speedRamp: 8,
      startSpawnDelay: 2.1,
      minSpawnDelay: 1.04,
      initialObstacles: 1,
    },
    hard: {
      startSpeed: 330,
      speedRamp: 13,
      startSpawnDelay: 1.52,
      minSpawnDelay: 0.74,
      initialObstacles: 2,
    },
  },
  storage: {
    bestTimeKey: 'sanfermin-runner:best-time',
    bestTimeByDifficultyKey: 'sanfermin-runner:best-time-by-difficulty',
    languageKey: 'sanfermin-runner:language',
    runnerKey: 'sanfermin-runner:selected-runner',
    scoresKey: 'sanfermin-runner:scores-by-difficulty',
  },
};
